name: CI_mypy

on: [pull_request, push]

jobs:
  run_mypy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install mypy
      run: sudo apt-get install -y mypy
    - name: Create default local config
      run: cp chj/util/ConfigLocal.template chj/util/ConfigLocal.py
    - name: Run mypy
      run: |
        PYTHONPATH=$PWD mypy chj/app chj/cost chj/index chj/libsum chj/reporting chj/util
